// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using workshop.wwwapi.Data;

#nullable disable

namespace workshop.wwwapi.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240201141253_firstMigration")]
    partial class firstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("workshop.wwwapi.Models.Appointment", b =>
                {
                    b.Property<int>("PatientId")
                        .HasColumnType("integer")
                        .HasColumnName("patient_id");

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer")
                        .HasColumnName("doctor_id");

                    b.Property<DateTimeOffset>("Booking")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.HasKey("PatientId", "DoctorId");

                    b.HasIndex("DoctorId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            PatientId = 24,
                            DoctorId = 2,
                            Booking = new DateTimeOffset(new DateTime(2024, 1, 21, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(896), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 1
                        },
                        new
                        {
                            PatientId = 245,
                            DoctorId = 6,
                            Booking = new DateTimeOffset(new DateTime(2024, 2, 14, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(995), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 2
                        },
                        new
                        {
                            PatientId = 3,
                            DoctorId = 2,
                            Booking = new DateTimeOffset(new DateTime(2024, 2, 18, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(999), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 3
                        },
                        new
                        {
                            PatientId = 19,
                            DoctorId = 10,
                            Booking = new DateTimeOffset(new DateTime(2024, 2, 14, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1002), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 4
                        },
                        new
                        {
                            PatientId = 188,
                            DoctorId = 2,
                            Booking = new DateTimeOffset(new DateTime(2024, 2, 6, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1010), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 5
                        },
                        new
                        {
                            PatientId = 200,
                            DoctorId = 6,
                            Booking = new DateTimeOffset(new DateTime(2024, 1, 22, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1014), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 6
                        },
                        new
                        {
                            PatientId = 59,
                            DoctorId = 7,
                            Booking = new DateTimeOffset(new DateTime(2024, 1, 4, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1018), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 7
                        },
                        new
                        {
                            PatientId = 249,
                            DoctorId = 9,
                            Booking = new DateTimeOffset(new DateTime(2024, 1, 21, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1021), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 8
                        },
                        new
                        {
                            PatientId = 23,
                            DoctorId = 8,
                            Booking = new DateTimeOffset(new DateTime(2024, 1, 23, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1026), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 9
                        },
                        new
                        {
                            PatientId = 81,
                            DoctorId = 3,
                            Booking = new DateTimeOffset(new DateTime(2024, 1, 12, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1030), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 10
                        },
                        new
                        {
                            PatientId = 177,
                            DoctorId = 4,
                            Booking = new DateTimeOffset(new DateTime(2024, 2, 22, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1034), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 11
                        },
                        new
                        {
                            PatientId = 137,
                            DoctorId = 9,
                            Booking = new DateTimeOffset(new DateTime(2024, 1, 2, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1037), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 12
                        },
                        new
                        {
                            PatientId = 44,
                            DoctorId = 8,
                            Booking = new DateTimeOffset(new DateTime(2024, 2, 21, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1072), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 13
                        },
                        new
                        {
                            PatientId = 192,
                            DoctorId = 9,
                            Booking = new DateTimeOffset(new DateTime(2024, 1, 5, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1076), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 14
                        },
                        new
                        {
                            PatientId = 220,
                            DoctorId = 5,
                            Booking = new DateTimeOffset(new DateTime(2024, 1, 10, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1079), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 15
                        },
                        new
                        {
                            PatientId = 72,
                            DoctorId = 2,
                            Booking = new DateTimeOffset(new DateTime(2024, 2, 25, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1083), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 16
                        },
                        new
                        {
                            PatientId = 172,
                            DoctorId = 2,
                            Booking = new DateTimeOffset(new DateTime(2024, 1, 13, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1086), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 17
                        },
                        new
                        {
                            PatientId = 58,
                            DoctorId = 2,
                            Booking = new DateTimeOffset(new DateTime(2024, 2, 24, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1090), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 18
                        },
                        new
                        {
                            PatientId = 144,
                            DoctorId = 8,
                            Booking = new DateTimeOffset(new DateTime(2024, 1, 19, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1096), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 19
                        },
                        new
                        {
                            PatientId = 147,
                            DoctorId = 6,
                            Booking = new DateTimeOffset(new DateTime(2024, 2, 11, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1099), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 20
                        },
                        new
                        {
                            PatientId = 76,
                            DoctorId = 5,
                            Booking = new DateTimeOffset(new DateTime(2024, 1, 8, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1102), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 21
                        },
                        new
                        {
                            PatientId = 108,
                            DoctorId = 4,
                            Booking = new DateTimeOffset(new DateTime(2024, 1, 2, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1105), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 22
                        },
                        new
                        {
                            PatientId = 73,
                            DoctorId = 8,
                            Booking = new DateTimeOffset(new DateTime(2024, 1, 9, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1108), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 23
                        },
                        new
                        {
                            PatientId = 79,
                            DoctorId = 2,
                            Booking = new DateTimeOffset(new DateTime(2024, 2, 2, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1111), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 24
                        },
                        new
                        {
                            PatientId = 59,
                            DoctorId = 10,
                            Booking = new DateTimeOffset(new DateTime(2024, 1, 9, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1114), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 25
                        },
                        new
                        {
                            PatientId = 208,
                            DoctorId = 9,
                            Booking = new DateTimeOffset(new DateTime(2024, 1, 18, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1117), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 26
                        },
                        new
                        {
                            PatientId = 126,
                            DoctorId = 5,
                            Booking = new DateTimeOffset(new DateTime(2024, 2, 5, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1119), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 27
                        },
                        new
                        {
                            PatientId = 93,
                            DoctorId = 7,
                            Booking = new DateTimeOffset(new DateTime(2024, 1, 4, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1122), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 28
                        },
                        new
                        {
                            PatientId = 71,
                            DoctorId = 1,
                            Booking = new DateTimeOffset(new DateTime(2024, 1, 23, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1125), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 29
                        },
                        new
                        {
                            PatientId = 123,
                            DoctorId = 2,
                            Booking = new DateTimeOffset(new DateTime(2024, 1, 15, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1128), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 30
                        },
                        new
                        {
                            PatientId = 91,
                            DoctorId = 2,
                            Booking = new DateTimeOffset(new DateTime(2024, 2, 29, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1131), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 31
                        },
                        new
                        {
                            PatientId = 128,
                            DoctorId = 5,
                            Booking = new DateTimeOffset(new DateTime(2024, 1, 30, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1134), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 32
                        },
                        new
                        {
                            PatientId = 107,
                            DoctorId = 7,
                            Booking = new DateTimeOffset(new DateTime(2024, 1, 11, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1136), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 33
                        },
                        new
                        {
                            PatientId = 103,
                            DoctorId = 8,
                            Booking = new DateTimeOffset(new DateTime(2024, 1, 2, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1140), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 34
                        },
                        new
                        {
                            PatientId = 27,
                            DoctorId = 6,
                            Booking = new DateTimeOffset(new DateTime(2024, 2, 20, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1143), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 35
                        },
                        new
                        {
                            PatientId = 7,
                            DoctorId = 6,
                            Booking = new DateTimeOffset(new DateTime(2024, 2, 7, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1146), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 36
                        },
                        new
                        {
                            PatientId = 51,
                            DoctorId = 5,
                            Booking = new DateTimeOffset(new DateTime(2024, 2, 20, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1149), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 37
                        },
                        new
                        {
                            PatientId = 1,
                            DoctorId = 3,
                            Booking = new DateTimeOffset(new DateTime(2024, 2, 1, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1152), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 38
                        },
                        new
                        {
                            PatientId = 151,
                            DoctorId = 4,
                            Booking = new DateTimeOffset(new DateTime(2024, 1, 22, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1161), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 39
                        },
                        new
                        {
                            PatientId = 230,
                            DoctorId = 4,
                            Booking = new DateTimeOffset(new DateTime(2024, 2, 13, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1163), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 40
                        },
                        new
                        {
                            PatientId = 69,
                            DoctorId = 3,
                            Booking = new DateTimeOffset(new DateTime(2024, 2, 14, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1166), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 41
                        },
                        new
                        {
                            PatientId = 201,
                            DoctorId = 1,
                            Booking = new DateTimeOffset(new DateTime(2024, 3, 1, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1169), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 42
                        },
                        new
                        {
                            PatientId = 20,
                            DoctorId = 1,
                            Booking = new DateTimeOffset(new DateTime(2024, 1, 12, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1171), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 43
                        },
                        new
                        {
                            PatientId = 22,
                            DoctorId = 2,
                            Booking = new DateTimeOffset(new DateTime(2024, 2, 24, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1174), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 44
                        },
                        new
                        {
                            PatientId = 141,
                            DoctorId = 10,
                            Booking = new DateTimeOffset(new DateTime(2024, 2, 29, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1177), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 45
                        },
                        new
                        {
                            PatientId = 48,
                            DoctorId = 8,
                            Booking = new DateTimeOffset(new DateTime(2024, 1, 26, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1180), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 46
                        },
                        new
                        {
                            PatientId = 11,
                            DoctorId = 9,
                            Booking = new DateTimeOffset(new DateTime(2024, 1, 7, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1183), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 47
                        },
                        new
                        {
                            PatientId = 159,
                            DoctorId = 3,
                            Booking = new DateTimeOffset(new DateTime(2024, 2, 17, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1186), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 48
                        },
                        new
                        {
                            PatientId = 70,
                            DoctorId = 5,
                            Booking = new DateTimeOffset(new DateTime(2024, 1, 29, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1189), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 49
                        },
                        new
                        {
                            PatientId = 81,
                            DoctorId = 7,
                            Booking = new DateTimeOffset(new DateTime(2024, 1, 18, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1192), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 50
                        },
                        new
                        {
                            PatientId = 143,
                            DoctorId = 9,
                            Booking = new DateTimeOffset(new DateTime(2024, 1, 30, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1194), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 51
                        },
                        new
                        {
                            PatientId = 170,
                            DoctorId = 8,
                            Booking = new DateTimeOffset(new DateTime(2024, 2, 19, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1197), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 52
                        },
                        new
                        {
                            PatientId = 155,
                            DoctorId = 4,
                            Booking = new DateTimeOffset(new DateTime(2024, 1, 25, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1200), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 53
                        },
                        new
                        {
                            PatientId = 85,
                            DoctorId = 1,
                            Booking = new DateTimeOffset(new DateTime(2024, 2, 14, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1203), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 54
                        },
                        new
                        {
                            PatientId = 174,
                            DoctorId = 4,
                            Booking = new DateTimeOffset(new DateTime(2024, 1, 3, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1206), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 55
                        },
                        new
                        {
                            PatientId = 118,
                            DoctorId = 7,
                            Booking = new DateTimeOffset(new DateTime(2024, 1, 29, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1209), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 56
                        },
                        new
                        {
                            PatientId = 94,
                            DoctorId = 9,
                            Booking = new DateTimeOffset(new DateTime(2024, 2, 15, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1212), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 57
                        },
                        new
                        {
                            PatientId = 108,
                            DoctorId = 7,
                            Booking = new DateTimeOffset(new DateTime(2024, 2, 12, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1215), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 58
                        },
                        new
                        {
                            PatientId = 27,
                            DoctorId = 8,
                            Booking = new DateTimeOffset(new DateTime(2024, 2, 10, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1218), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 59
                        },
                        new
                        {
                            PatientId = 140,
                            DoctorId = 3,
                            Booking = new DateTimeOffset(new DateTime(2024, 2, 23, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1221), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 60
                        },
                        new
                        {
                            PatientId = 170,
                            DoctorId = 10,
                            Booking = new DateTimeOffset(new DateTime(2024, 2, 21, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1224), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 61
                        },
                        new
                        {
                            PatientId = 3,
                            DoctorId = 10,
                            Booking = new DateTimeOffset(new DateTime(2024, 3, 1, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1226), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 62
                        },
                        new
                        {
                            PatientId = 18,
                            DoctorId = 9,
                            Booking = new DateTimeOffset(new DateTime(2024, 1, 12, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1229), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 63
                        },
                        new
                        {
                            PatientId = 18,
                            DoctorId = 1,
                            Booking = new DateTimeOffset(new DateTime(2024, 2, 22, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1232), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 64
                        },
                        new
                        {
                            PatientId = 132,
                            DoctorId = 9,
                            Booking = new DateTimeOffset(new DateTime(2024, 2, 4, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1235), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 65
                        },
                        new
                        {
                            PatientId = 46,
                            DoctorId = 7,
                            Booking = new DateTimeOffset(new DateTime(2024, 1, 15, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1239), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 66
                        },
                        new
                        {
                            PatientId = 230,
                            DoctorId = 8,
                            Booking = new DateTimeOffset(new DateTime(2024, 1, 4, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1242), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 67
                        },
                        new
                        {
                            PatientId = 175,
                            DoctorId = 7,
                            Booking = new DateTimeOffset(new DateTime(2024, 2, 14, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1245), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 68
                        },
                        new
                        {
                            PatientId = 212,
                            DoctorId = 9,
                            Booking = new DateTimeOffset(new DateTime(2024, 1, 28, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1248), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 69
                        },
                        new
                        {
                            PatientId = 4,
                            DoctorId = 8,
                            Booking = new DateTimeOffset(new DateTime(2024, 1, 17, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1251), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 70
                        },
                        new
                        {
                            PatientId = 40,
                            DoctorId = 2,
                            Booking = new DateTimeOffset(new DateTime(2024, 2, 5, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1283), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 71
                        },
                        new
                        {
                            PatientId = 98,
                            DoctorId = 2,
                            Booking = new DateTimeOffset(new DateTime(2024, 2, 21, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1287), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 72
                        },
                        new
                        {
                            PatientId = 191,
                            DoctorId = 2,
                            Booking = new DateTimeOffset(new DateTime(2024, 2, 11, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1289), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 73
                        },
                        new
                        {
                            PatientId = 74,
                            DoctorId = 3,
                            Booking = new DateTimeOffset(new DateTime(2024, 1, 8, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1292), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 74
                        },
                        new
                        {
                            PatientId = 45,
                            DoctorId = 1,
                            Booking = new DateTimeOffset(new DateTime(2024, 1, 29, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1295), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 75
                        },
                        new
                        {
                            PatientId = 208,
                            DoctorId = 8,
                            Booking = new DateTimeOffset(new DateTime(2024, 1, 29, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1299), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 76
                        },
                        new
                        {
                            PatientId = 126,
                            DoctorId = 3,
                            Booking = new DateTimeOffset(new DateTime(2024, 1, 10, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1303), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 77
                        },
                        new
                        {
                            PatientId = 111,
                            DoctorId = 10,
                            Booking = new DateTimeOffset(new DateTime(2024, 2, 25, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1306), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 78
                        },
                        new
                        {
                            PatientId = 84,
                            DoctorId = 7,
                            Booking = new DateTimeOffset(new DateTime(2024, 1, 14, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1309), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 79
                        },
                        new
                        {
                            PatientId = 22,
                            DoctorId = 10,
                            Booking = new DateTimeOffset(new DateTime(2024, 2, 2, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1313), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 80
                        },
                        new
                        {
                            PatientId = 220,
                            DoctorId = 1,
                            Booking = new DateTimeOffset(new DateTime(2024, 1, 29, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1315), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 81
                        },
                        new
                        {
                            PatientId = 34,
                            DoctorId = 1,
                            Booking = new DateTimeOffset(new DateTime(2024, 2, 12, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1318), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 82
                        },
                        new
                        {
                            PatientId = 112,
                            DoctorId = 1,
                            Booking = new DateTimeOffset(new DateTime(2024, 2, 7, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1321), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 83
                        },
                        new
                        {
                            PatientId = 102,
                            DoctorId = 4,
                            Booking = new DateTimeOffset(new DateTime(2024, 1, 17, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1324), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 84
                        },
                        new
                        {
                            PatientId = 25,
                            DoctorId = 6,
                            Booking = new DateTimeOffset(new DateTime(2024, 2, 2, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1327), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 85
                        },
                        new
                        {
                            PatientId = 90,
                            DoctorId = 5,
                            Booking = new DateTimeOffset(new DateTime(2024, 1, 23, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1330), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 86
                        },
                        new
                        {
                            PatientId = 198,
                            DoctorId = 4,
                            Booking = new DateTimeOffset(new DateTime(2024, 2, 23, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1334), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 87
                        },
                        new
                        {
                            PatientId = 65,
                            DoctorId = 1,
                            Booking = new DateTimeOffset(new DateTime(2024, 1, 14, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1347), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 89
                        },
                        new
                        {
                            PatientId = 16,
                            DoctorId = 8,
                            Booking = new DateTimeOffset(new DateTime(2024, 2, 6, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1350), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 90
                        },
                        new
                        {
                            PatientId = 28,
                            DoctorId = 4,
                            Booking = new DateTimeOffset(new DateTime(2024, 1, 30, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1354), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 91
                        },
                        new
                        {
                            PatientId = 158,
                            DoctorId = 8,
                            Booking = new DateTimeOffset(new DateTime(2024, 1, 12, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1369), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 92
                        },
                        new
                        {
                            PatientId = 198,
                            DoctorId = 2,
                            Booking = new DateTimeOffset(new DateTime(2024, 1, 6, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1371), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 93
                        },
                        new
                        {
                            PatientId = 95,
                            DoctorId = 9,
                            Booking = new DateTimeOffset(new DateTime(2024, 1, 18, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1374), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 94
                        },
                        new
                        {
                            PatientId = 182,
                            DoctorId = 3,
                            Booking = new DateTimeOffset(new DateTime(2024, 1, 20, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1377), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 95
                        },
                        new
                        {
                            PatientId = 39,
                            DoctorId = 9,
                            Booking = new DateTimeOffset(new DateTime(2024, 3, 1, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1380), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 96
                        },
                        new
                        {
                            PatientId = 44,
                            DoctorId = 10,
                            Booking = new DateTimeOffset(new DateTime(2024, 1, 10, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1383), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 97
                        },
                        new
                        {
                            PatientId = 188,
                            DoctorId = 6,
                            Booking = new DateTimeOffset(new DateTime(2024, 2, 6, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1386), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 98
                        },
                        new
                        {
                            PatientId = 25,
                            DoctorId = 7,
                            Booking = new DateTimeOffset(new DateTime(2024, 2, 17, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1388), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 99
                        },
                        new
                        {
                            PatientId = 99,
                            DoctorId = 3,
                            Booking = new DateTimeOffset(new DateTime(2024, 1, 17, 15, 12, 53, 324, DateTimeKind.Unspecified).AddTicks(1391), new TimeSpan(0, 1, 0, 0, 0)),
                            Id = 100
                        });
                });

            modelBuilder.Entity("workshop.wwwapi.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.HasKey("Id");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Mick Winfrey"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Elvis Jagger"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Elvis Hepburn"
                        },
                        new
                        {
                            Id = 4,
                            FullName = "Donald Winfrey"
                        },
                        new
                        {
                            Id = 5,
                            FullName = "Kate Hepburn"
                        },
                        new
                        {
                            Id = 6,
                            FullName = "Elvis Trump"
                        },
                        new
                        {
                            Id = 7,
                            FullName = "Kate Presley"
                        },
                        new
                        {
                            Id = 8,
                            FullName = "Jimi Winslet"
                        },
                        new
                        {
                            Id = 9,
                            FullName = "Jimi Obama"
                        },
                        new
                        {
                            Id = 10,
                            FullName = "Elvis Windsor"
                        });
                });

            modelBuilder.Entity("workshop.wwwapi.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DoctorId = 2,
                            FullName = "Jimi Trump"
                        },
                        new
                        {
                            Id = 2,
                            DoctorId = 7,
                            FullName = "Kate Middleton"
                        },
                        new
                        {
                            Id = 3,
                            DoctorId = 2,
                            FullName = "Oprah Obama"
                        },
                        new
                        {
                            Id = 4,
                            DoctorId = 2,
                            FullName = "Charles Hepburn"
                        },
                        new
                        {
                            Id = 5,
                            DoctorId = 8,
                            FullName = "Donald Winslet"
                        },
                        new
                        {
                            Id = 6,
                            DoctorId = 7,
                            FullName = "Donald Windsor"
                        },
                        new
                        {
                            Id = 7,
                            DoctorId = 4,
                            FullName = "Charles Winfrey"
                        },
                        new
                        {
                            Id = 8,
                            DoctorId = 8,
                            FullName = "Elvis Middleton"
                        },
                        new
                        {
                            Id = 9,
                            DoctorId = 3,
                            FullName = "Charles Obama"
                        },
                        new
                        {
                            Id = 10,
                            DoctorId = 10,
                            FullName = "Barack Hendrix"
                        },
                        new
                        {
                            Id = 11,
                            DoctorId = 2,
                            FullName = "Jimi Jagger"
                        },
                        new
                        {
                            Id = 12,
                            DoctorId = 9,
                            FullName = "Oprah Hendrix"
                        },
                        new
                        {
                            Id = 13,
                            DoctorId = 3,
                            FullName = "Elvis Obama"
                        },
                        new
                        {
                            Id = 14,
                            DoctorId = 10,
                            FullName = "Audrey Middleton"
                        },
                        new
                        {
                            Id = 15,
                            DoctorId = 7,
                            FullName = "Donald Hepburn"
                        },
                        new
                        {
                            Id = 16,
                            DoctorId = 7,
                            FullName = "Kate Winslet"
                        },
                        new
                        {
                            Id = 17,
                            DoctorId = 7,
                            FullName = "Audrey Winslet"
                        },
                        new
                        {
                            Id = 18,
                            DoctorId = 7,
                            FullName = "Kate Presley"
                        },
                        new
                        {
                            Id = 19,
                            DoctorId = 8,
                            FullName = "Oprah Hepburn"
                        },
                        new
                        {
                            Id = 20,
                            DoctorId = 1,
                            FullName = "Kate Winslet"
                        },
                        new
                        {
                            Id = 21,
                            DoctorId = 6,
                            FullName = "Mick Hendrix"
                        },
                        new
                        {
                            Id = 22,
                            DoctorId = 8,
                            FullName = "Elvis Jagger"
                        },
                        new
                        {
                            Id = 23,
                            DoctorId = 7,
                            FullName = "Oprah Middleton"
                        },
                        new
                        {
                            Id = 24,
                            DoctorId = 9,
                            FullName = "Jimi Winfrey"
                        },
                        new
                        {
                            Id = 25,
                            DoctorId = 9,
                            FullName = "Jimi Jagger"
                        },
                        new
                        {
                            Id = 26,
                            DoctorId = 2,
                            FullName = "Oprah Hendrix"
                        },
                        new
                        {
                            Id = 27,
                            DoctorId = 10,
                            FullName = "Oprah Middleton"
                        },
                        new
                        {
                            Id = 28,
                            DoctorId = 4,
                            FullName = "Kate Jagger"
                        },
                        new
                        {
                            Id = 29,
                            DoctorId = 9,
                            FullName = "Kate Trump"
                        },
                        new
                        {
                            Id = 30,
                            DoctorId = 5,
                            FullName = "Kate Jagger"
                        },
                        new
                        {
                            Id = 31,
                            DoctorId = 4,
                            FullName = "Kate Jagger"
                        },
                        new
                        {
                            Id = 32,
                            DoctorId = 8,
                            FullName = "Charles Presley"
                        },
                        new
                        {
                            Id = 33,
                            DoctorId = 10,
                            FullName = "Oprah Windsor"
                        },
                        new
                        {
                            Id = 34,
                            DoctorId = 1,
                            FullName = "Jimi Middleton"
                        },
                        new
                        {
                            Id = 35,
                            DoctorId = 8,
                            FullName = "Elvis Presley"
                        },
                        new
                        {
                            Id = 36,
                            DoctorId = 2,
                            FullName = "Charles Presley"
                        },
                        new
                        {
                            Id = 37,
                            DoctorId = 6,
                            FullName = "Mick Middleton"
                        },
                        new
                        {
                            Id = 38,
                            DoctorId = 7,
                            FullName = "Charles Windsor"
                        },
                        new
                        {
                            Id = 39,
                            DoctorId = 10,
                            FullName = "Barack Winslet"
                        },
                        new
                        {
                            Id = 40,
                            DoctorId = 6,
                            FullName = "Mick Jagger"
                        },
                        new
                        {
                            Id = 41,
                            DoctorId = 4,
                            FullName = "Jimi Presley"
                        },
                        new
                        {
                            Id = 42,
                            DoctorId = 3,
                            FullName = "Oprah Hendrix"
                        },
                        new
                        {
                            Id = 43,
                            DoctorId = 5,
                            FullName = "Kate Middleton"
                        },
                        new
                        {
                            Id = 44,
                            DoctorId = 1,
                            FullName = "Charles Obama"
                        },
                        new
                        {
                            Id = 45,
                            DoctorId = 9,
                            FullName = "Elvis Winslet"
                        },
                        new
                        {
                            Id = 46,
                            DoctorId = 9,
                            FullName = "Mick Obama"
                        },
                        new
                        {
                            Id = 47,
                            DoctorId = 7,
                            FullName = "Kate Trump"
                        },
                        new
                        {
                            Id = 48,
                            DoctorId = 9,
                            FullName = "Elvis Presley"
                        },
                        new
                        {
                            Id = 49,
                            DoctorId = 7,
                            FullName = "Barack Hendrix"
                        },
                        new
                        {
                            Id = 50,
                            DoctorId = 6,
                            FullName = "Kate Presley"
                        },
                        new
                        {
                            Id = 51,
                            DoctorId = 8,
                            FullName = "Charles Jagger"
                        },
                        new
                        {
                            Id = 52,
                            DoctorId = 10,
                            FullName = "Donald Middleton"
                        },
                        new
                        {
                            Id = 53,
                            DoctorId = 5,
                            FullName = "Elvis Jagger"
                        },
                        new
                        {
                            Id = 54,
                            DoctorId = 9,
                            FullName = "Elvis Winfrey"
                        },
                        new
                        {
                            Id = 55,
                            DoctorId = 5,
                            FullName = "Jimi Windsor"
                        },
                        new
                        {
                            Id = 56,
                            DoctorId = 8,
                            FullName = "Kate Winslet"
                        },
                        new
                        {
                            Id = 57,
                            DoctorId = 3,
                            FullName = "Donald Middleton"
                        },
                        new
                        {
                            Id = 58,
                            DoctorId = 6,
                            FullName = "Oprah Jagger"
                        },
                        new
                        {
                            Id = 59,
                            DoctorId = 1,
                            FullName = "Charles Hepburn"
                        },
                        new
                        {
                            Id = 60,
                            DoctorId = 6,
                            FullName = "Audrey Winfrey"
                        },
                        new
                        {
                            Id = 61,
                            DoctorId = 1,
                            FullName = "Audrey Obama"
                        },
                        new
                        {
                            Id = 62,
                            DoctorId = 3,
                            FullName = "Mick Windsor"
                        },
                        new
                        {
                            Id = 63,
                            DoctorId = 9,
                            FullName = "Audrey Obama"
                        },
                        new
                        {
                            Id = 64,
                            DoctorId = 9,
                            FullName = "Kate Middleton"
                        },
                        new
                        {
                            Id = 65,
                            DoctorId = 8,
                            FullName = "Mick Windsor"
                        },
                        new
                        {
                            Id = 66,
                            DoctorId = 2,
                            FullName = "Elvis Winfrey"
                        },
                        new
                        {
                            Id = 67,
                            DoctorId = 1,
                            FullName = "Elvis Middleton"
                        },
                        new
                        {
                            Id = 68,
                            DoctorId = 10,
                            FullName = "Kate Winslet"
                        },
                        new
                        {
                            Id = 69,
                            DoctorId = 7,
                            FullName = "Audrey Windsor"
                        },
                        new
                        {
                            Id = 70,
                            DoctorId = 5,
                            FullName = "Audrey Trump"
                        },
                        new
                        {
                            Id = 71,
                            DoctorId = 4,
                            FullName = "Charles Hepburn"
                        },
                        new
                        {
                            Id = 72,
                            DoctorId = 6,
                            FullName = "Kate Hepburn"
                        },
                        new
                        {
                            Id = 73,
                            DoctorId = 4,
                            FullName = "Barack Hendrix"
                        },
                        new
                        {
                            Id = 74,
                            DoctorId = 7,
                            FullName = "Elvis Windsor"
                        },
                        new
                        {
                            Id = 75,
                            DoctorId = 10,
                            FullName = "Audrey Presley"
                        },
                        new
                        {
                            Id = 76,
                            DoctorId = 5,
                            FullName = "Mick Presley"
                        },
                        new
                        {
                            Id = 77,
                            DoctorId = 2,
                            FullName = "Charles Trump"
                        },
                        new
                        {
                            Id = 78,
                            DoctorId = 1,
                            FullName = "Barack Winfrey"
                        },
                        new
                        {
                            Id = 79,
                            DoctorId = 4,
                            FullName = "Charles Presley"
                        },
                        new
                        {
                            Id = 80,
                            DoctorId = 9,
                            FullName = "Oprah Jagger"
                        },
                        new
                        {
                            Id = 81,
                            DoctorId = 3,
                            FullName = "Barack Hepburn"
                        },
                        new
                        {
                            Id = 82,
                            DoctorId = 5,
                            FullName = "Charles Hepburn"
                        },
                        new
                        {
                            Id = 83,
                            DoctorId = 8,
                            FullName = "Barack Obama"
                        },
                        new
                        {
                            Id = 84,
                            DoctorId = 7,
                            FullName = "Kate Jagger"
                        },
                        new
                        {
                            Id = 85,
                            DoctorId = 5,
                            FullName = "Jimi Winslet"
                        },
                        new
                        {
                            Id = 86,
                            DoctorId = 1,
                            FullName = "Donald Hendrix"
                        },
                        new
                        {
                            Id = 87,
                            DoctorId = 5,
                            FullName = "Donald Hepburn"
                        },
                        new
                        {
                            Id = 88,
                            DoctorId = 10,
                            FullName = "Jimi Trump"
                        },
                        new
                        {
                            Id = 89,
                            DoctorId = 9,
                            FullName = "Jimi Hendrix"
                        },
                        new
                        {
                            Id = 90,
                            DoctorId = 2,
                            FullName = "Kate Windsor"
                        },
                        new
                        {
                            Id = 91,
                            DoctorId = 3,
                            FullName = "Donald Windsor"
                        },
                        new
                        {
                            Id = 92,
                            DoctorId = 6,
                            FullName = "Kate Presley"
                        },
                        new
                        {
                            Id = 93,
                            DoctorId = 3,
                            FullName = "Audrey Trump"
                        },
                        new
                        {
                            Id = 94,
                            DoctorId = 10,
                            FullName = "Donald Hendrix"
                        },
                        new
                        {
                            Id = 95,
                            DoctorId = 2,
                            FullName = "Charles Winslet"
                        },
                        new
                        {
                            Id = 96,
                            DoctorId = 10,
                            FullName = "Jimi Hendrix"
                        },
                        new
                        {
                            Id = 97,
                            DoctorId = 8,
                            FullName = "Oprah Windsor"
                        },
                        new
                        {
                            Id = 98,
                            DoctorId = 9,
                            FullName = "Audrey Jagger"
                        },
                        new
                        {
                            Id = 99,
                            DoctorId = 5,
                            FullName = "Charles Hendrix"
                        },
                        new
                        {
                            Id = 100,
                            DoctorId = 6,
                            FullName = "Donald Windsor"
                        },
                        new
                        {
                            Id = 101,
                            DoctorId = 8,
                            FullName = "Kate Hepburn"
                        },
                        new
                        {
                            Id = 102,
                            DoctorId = 1,
                            FullName = "Audrey Middleton"
                        },
                        new
                        {
                            Id = 103,
                            DoctorId = 4,
                            FullName = "Charles Winslet"
                        },
                        new
                        {
                            Id = 104,
                            DoctorId = 5,
                            FullName = "Audrey Middleton"
                        },
                        new
                        {
                            Id = 105,
                            DoctorId = 3,
                            FullName = "Kate Jagger"
                        },
                        new
                        {
                            Id = 106,
                            DoctorId = 1,
                            FullName = "Jimi Hendrix"
                        },
                        new
                        {
                            Id = 107,
                            DoctorId = 3,
                            FullName = "Elvis Windsor"
                        },
                        new
                        {
                            Id = 108,
                            DoctorId = 6,
                            FullName = "Barack Middleton"
                        },
                        new
                        {
                            Id = 109,
                            DoctorId = 6,
                            FullName = "Jimi Winslet"
                        },
                        new
                        {
                            Id = 110,
                            DoctorId = 5,
                            FullName = "Mick Winfrey"
                        },
                        new
                        {
                            Id = 111,
                            DoctorId = 7,
                            FullName = "Oprah Winfrey"
                        },
                        new
                        {
                            Id = 112,
                            DoctorId = 10,
                            FullName = "Charles Middleton"
                        },
                        new
                        {
                            Id = 113,
                            DoctorId = 3,
                            FullName = "Audrey Windsor"
                        },
                        new
                        {
                            Id = 114,
                            DoctorId = 9,
                            FullName = "Donald Windsor"
                        },
                        new
                        {
                            Id = 115,
                            DoctorId = 9,
                            FullName = "Charles Winslet"
                        },
                        new
                        {
                            Id = 116,
                            DoctorId = 1,
                            FullName = "Barack Jagger"
                        },
                        new
                        {
                            Id = 117,
                            DoctorId = 5,
                            FullName = "Kate Hendrix"
                        },
                        new
                        {
                            Id = 118,
                            DoctorId = 9,
                            FullName = "Mick Presley"
                        },
                        new
                        {
                            Id = 119,
                            DoctorId = 7,
                            FullName = "Elvis Hepburn"
                        },
                        new
                        {
                            Id = 120,
                            DoctorId = 10,
                            FullName = "Charles Jagger"
                        },
                        new
                        {
                            Id = 121,
                            DoctorId = 1,
                            FullName = "Jimi Middleton"
                        },
                        new
                        {
                            Id = 122,
                            DoctorId = 1,
                            FullName = "Audrey Hendrix"
                        },
                        new
                        {
                            Id = 123,
                            DoctorId = 7,
                            FullName = "Charles Obama"
                        },
                        new
                        {
                            Id = 124,
                            DoctorId = 9,
                            FullName = "Audrey Middleton"
                        },
                        new
                        {
                            Id = 125,
                            DoctorId = 1,
                            FullName = "Kate Winslet"
                        },
                        new
                        {
                            Id = 126,
                            DoctorId = 4,
                            FullName = "Kate Windsor"
                        },
                        new
                        {
                            Id = 127,
                            DoctorId = 5,
                            FullName = "Jimi Hendrix"
                        },
                        new
                        {
                            Id = 128,
                            DoctorId = 2,
                            FullName = "Charles Middleton"
                        },
                        new
                        {
                            Id = 129,
                            DoctorId = 3,
                            FullName = "Charles Trump"
                        },
                        new
                        {
                            Id = 130,
                            DoctorId = 9,
                            FullName = "Charles Trump"
                        },
                        new
                        {
                            Id = 131,
                            DoctorId = 3,
                            FullName = "Mick Middleton"
                        },
                        new
                        {
                            Id = 132,
                            DoctorId = 1,
                            FullName = "Barack Middleton"
                        },
                        new
                        {
                            Id = 133,
                            DoctorId = 8,
                            FullName = "Kate Obama"
                        },
                        new
                        {
                            Id = 134,
                            DoctorId = 3,
                            FullName = "Charles Hendrix"
                        },
                        new
                        {
                            Id = 135,
                            DoctorId = 4,
                            FullName = "Elvis Windsor"
                        },
                        new
                        {
                            Id = 136,
                            DoctorId = 10,
                            FullName = "Oprah Jagger"
                        },
                        new
                        {
                            Id = 137,
                            DoctorId = 1,
                            FullName = "Jimi Jagger"
                        },
                        new
                        {
                            Id = 138,
                            DoctorId = 1,
                            FullName = "Kate Hepburn"
                        },
                        new
                        {
                            Id = 139,
                            DoctorId = 4,
                            FullName = "Jimi Trump"
                        },
                        new
                        {
                            Id = 140,
                            DoctorId = 3,
                            FullName = "Donald Jagger"
                        },
                        new
                        {
                            Id = 141,
                            DoctorId = 7,
                            FullName = "Kate Obama"
                        },
                        new
                        {
                            Id = 142,
                            DoctorId = 2,
                            FullName = "Donald Winslet"
                        },
                        new
                        {
                            Id = 143,
                            DoctorId = 5,
                            FullName = "Donald Hepburn"
                        },
                        new
                        {
                            Id = 144,
                            DoctorId = 9,
                            FullName = "Audrey Obama"
                        },
                        new
                        {
                            Id = 145,
                            DoctorId = 5,
                            FullName = "Charles Jagger"
                        },
                        new
                        {
                            Id = 146,
                            DoctorId = 2,
                            FullName = "Jimi Winslet"
                        },
                        new
                        {
                            Id = 147,
                            DoctorId = 3,
                            FullName = "Charles Trump"
                        },
                        new
                        {
                            Id = 148,
                            DoctorId = 4,
                            FullName = "Charles Obama"
                        },
                        new
                        {
                            Id = 149,
                            DoctorId = 10,
                            FullName = "Kate Jagger"
                        },
                        new
                        {
                            Id = 150,
                            DoctorId = 9,
                            FullName = "Kate Middleton"
                        },
                        new
                        {
                            Id = 151,
                            DoctorId = 6,
                            FullName = "Barack Jagger"
                        },
                        new
                        {
                            Id = 152,
                            DoctorId = 4,
                            FullName = "Jimi Jagger"
                        },
                        new
                        {
                            Id = 153,
                            DoctorId = 8,
                            FullName = "Jimi Middleton"
                        },
                        new
                        {
                            Id = 154,
                            DoctorId = 3,
                            FullName = "Jimi Windsor"
                        },
                        new
                        {
                            Id = 155,
                            DoctorId = 2,
                            FullName = "Donald Obama"
                        },
                        new
                        {
                            Id = 156,
                            DoctorId = 2,
                            FullName = "Oprah Winfrey"
                        },
                        new
                        {
                            Id = 157,
                            DoctorId = 1,
                            FullName = "Charles Trump"
                        },
                        new
                        {
                            Id = 158,
                            DoctorId = 6,
                            FullName = "Jimi Middleton"
                        },
                        new
                        {
                            Id = 159,
                            DoctorId = 7,
                            FullName = "Charles Winfrey"
                        },
                        new
                        {
                            Id = 160,
                            DoctorId = 6,
                            FullName = "Kate Hendrix"
                        },
                        new
                        {
                            Id = 161,
                            DoctorId = 4,
                            FullName = "Donald Hepburn"
                        },
                        new
                        {
                            Id = 162,
                            DoctorId = 6,
                            FullName = "Kate Hendrix"
                        },
                        new
                        {
                            Id = 163,
                            DoctorId = 2,
                            FullName = "Mick Hepburn"
                        },
                        new
                        {
                            Id = 164,
                            DoctorId = 2,
                            FullName = "Audrey Windsor"
                        },
                        new
                        {
                            Id = 165,
                            DoctorId = 1,
                            FullName = "Elvis Presley"
                        },
                        new
                        {
                            Id = 166,
                            DoctorId = 1,
                            FullName = "Kate Hendrix"
                        },
                        new
                        {
                            Id = 167,
                            DoctorId = 5,
                            FullName = "Mick Hendrix"
                        },
                        new
                        {
                            Id = 168,
                            DoctorId = 9,
                            FullName = "Kate Hendrix"
                        },
                        new
                        {
                            Id = 169,
                            DoctorId = 6,
                            FullName = "Elvis Obama"
                        },
                        new
                        {
                            Id = 170,
                            DoctorId = 10,
                            FullName = "Jimi Middleton"
                        },
                        new
                        {
                            Id = 171,
                            DoctorId = 5,
                            FullName = "Barack Windsor"
                        },
                        new
                        {
                            Id = 172,
                            DoctorId = 8,
                            FullName = "Elvis Trump"
                        },
                        new
                        {
                            Id = 173,
                            DoctorId = 4,
                            FullName = "Elvis Windsor"
                        },
                        new
                        {
                            Id = 174,
                            DoctorId = 10,
                            FullName = "Kate Winslet"
                        },
                        new
                        {
                            Id = 175,
                            DoctorId = 10,
                            FullName = "Oprah Middleton"
                        },
                        new
                        {
                            Id = 176,
                            DoctorId = 8,
                            FullName = "Barack Winfrey"
                        },
                        new
                        {
                            Id = 177,
                            DoctorId = 9,
                            FullName = "Oprah Middleton"
                        },
                        new
                        {
                            Id = 178,
                            DoctorId = 1,
                            FullName = "Audrey Jagger"
                        },
                        new
                        {
                            Id = 179,
                            DoctorId = 2,
                            FullName = "Elvis Winfrey"
                        },
                        new
                        {
                            Id = 180,
                            DoctorId = 7,
                            FullName = "Mick Presley"
                        },
                        new
                        {
                            Id = 181,
                            DoctorId = 5,
                            FullName = "Donald Winfrey"
                        },
                        new
                        {
                            Id = 182,
                            DoctorId = 5,
                            FullName = "Elvis Obama"
                        },
                        new
                        {
                            Id = 183,
                            DoctorId = 4,
                            FullName = "Kate Winfrey"
                        },
                        new
                        {
                            Id = 184,
                            DoctorId = 4,
                            FullName = "Kate Presley"
                        },
                        new
                        {
                            Id = 185,
                            DoctorId = 3,
                            FullName = "Oprah Hepburn"
                        },
                        new
                        {
                            Id = 186,
                            DoctorId = 1,
                            FullName = "Donald Windsor"
                        },
                        new
                        {
                            Id = 187,
                            DoctorId = 10,
                            FullName = "Donald Windsor"
                        },
                        new
                        {
                            Id = 188,
                            DoctorId = 7,
                            FullName = "Elvis Hendrix"
                        },
                        new
                        {
                            Id = 189,
                            DoctorId = 4,
                            FullName = "Donald Hendrix"
                        },
                        new
                        {
                            Id = 190,
                            DoctorId = 7,
                            FullName = "Donald Winslet"
                        },
                        new
                        {
                            Id = 191,
                            DoctorId = 6,
                            FullName = "Oprah Windsor"
                        },
                        new
                        {
                            Id = 192,
                            DoctorId = 10,
                            FullName = "Oprah Winfrey"
                        },
                        new
                        {
                            Id = 193,
                            DoctorId = 5,
                            FullName = "Barack Presley"
                        },
                        new
                        {
                            Id = 194,
                            DoctorId = 5,
                            FullName = "Audrey Jagger"
                        },
                        new
                        {
                            Id = 195,
                            DoctorId = 8,
                            FullName = "Oprah Windsor"
                        },
                        new
                        {
                            Id = 196,
                            DoctorId = 8,
                            FullName = "Mick Winslet"
                        },
                        new
                        {
                            Id = 197,
                            DoctorId = 9,
                            FullName = "Kate Obama"
                        },
                        new
                        {
                            Id = 198,
                            DoctorId = 5,
                            FullName = "Kate Winfrey"
                        },
                        new
                        {
                            Id = 199,
                            DoctorId = 1,
                            FullName = "Donald Winslet"
                        },
                        new
                        {
                            Id = 200,
                            DoctorId = 1,
                            FullName = "Charles Presley"
                        },
                        new
                        {
                            Id = 201,
                            DoctorId = 2,
                            FullName = "Oprah Winfrey"
                        },
                        new
                        {
                            Id = 202,
                            DoctorId = 1,
                            FullName = "Kate Hepburn"
                        },
                        new
                        {
                            Id = 203,
                            DoctorId = 5,
                            FullName = "Donald Obama"
                        },
                        new
                        {
                            Id = 204,
                            DoctorId = 3,
                            FullName = "Charles Winfrey"
                        },
                        new
                        {
                            Id = 205,
                            DoctorId = 7,
                            FullName = "Donald Hepburn"
                        },
                        new
                        {
                            Id = 206,
                            DoctorId = 6,
                            FullName = "Kate Hepburn"
                        },
                        new
                        {
                            Id = 207,
                            DoctorId = 3,
                            FullName = "Kate Hendrix"
                        },
                        new
                        {
                            Id = 208,
                            DoctorId = 7,
                            FullName = "Charles Hepburn"
                        },
                        new
                        {
                            Id = 209,
                            DoctorId = 10,
                            FullName = "Kate Winfrey"
                        },
                        new
                        {
                            Id = 210,
                            DoctorId = 6,
                            FullName = "Audrey Winfrey"
                        },
                        new
                        {
                            Id = 211,
                            DoctorId = 10,
                            FullName = "Mick Trump"
                        },
                        new
                        {
                            Id = 212,
                            DoctorId = 7,
                            FullName = "Kate Winfrey"
                        },
                        new
                        {
                            Id = 213,
                            DoctorId = 5,
                            FullName = "Kate Winslet"
                        },
                        new
                        {
                            Id = 214,
                            DoctorId = 2,
                            FullName = "Kate Winslet"
                        },
                        new
                        {
                            Id = 215,
                            DoctorId = 6,
                            FullName = "Charles Obama"
                        },
                        new
                        {
                            Id = 216,
                            DoctorId = 10,
                            FullName = "Audrey Middleton"
                        },
                        new
                        {
                            Id = 217,
                            DoctorId = 10,
                            FullName = "Charles Jagger"
                        },
                        new
                        {
                            Id = 218,
                            DoctorId = 1,
                            FullName = "Kate Hepburn"
                        },
                        new
                        {
                            Id = 219,
                            DoctorId = 1,
                            FullName = "Audrey Jagger"
                        },
                        new
                        {
                            Id = 220,
                            DoctorId = 2,
                            FullName = "Donald Trump"
                        },
                        new
                        {
                            Id = 221,
                            DoctorId = 10,
                            FullName = "Kate Jagger"
                        },
                        new
                        {
                            Id = 222,
                            DoctorId = 5,
                            FullName = "Kate Hepburn"
                        },
                        new
                        {
                            Id = 223,
                            DoctorId = 8,
                            FullName = "Donald Middleton"
                        },
                        new
                        {
                            Id = 224,
                            DoctorId = 1,
                            FullName = "Barack Hepburn"
                        },
                        new
                        {
                            Id = 225,
                            DoctorId = 9,
                            FullName = "Jimi Presley"
                        },
                        new
                        {
                            Id = 226,
                            DoctorId = 1,
                            FullName = "Elvis Middleton"
                        },
                        new
                        {
                            Id = 227,
                            DoctorId = 2,
                            FullName = "Kate Hendrix"
                        },
                        new
                        {
                            Id = 228,
                            DoctorId = 7,
                            FullName = "Jimi Hepburn"
                        },
                        new
                        {
                            Id = 229,
                            DoctorId = 8,
                            FullName = "Donald Winfrey"
                        },
                        new
                        {
                            Id = 230,
                            DoctorId = 6,
                            FullName = "Barack Winslet"
                        },
                        new
                        {
                            Id = 231,
                            DoctorId = 9,
                            FullName = "Jimi Windsor"
                        },
                        new
                        {
                            Id = 232,
                            DoctorId = 6,
                            FullName = "Elvis Windsor"
                        },
                        new
                        {
                            Id = 233,
                            DoctorId = 4,
                            FullName = "Kate Hepburn"
                        },
                        new
                        {
                            Id = 234,
                            DoctorId = 4,
                            FullName = "Charles Hepburn"
                        },
                        new
                        {
                            Id = 235,
                            DoctorId = 9,
                            FullName = "Oprah Winslet"
                        },
                        new
                        {
                            Id = 236,
                            DoctorId = 4,
                            FullName = "Kate Jagger"
                        },
                        new
                        {
                            Id = 237,
                            DoctorId = 2,
                            FullName = "Kate Obama"
                        },
                        new
                        {
                            Id = 238,
                            DoctorId = 9,
                            FullName = "Barack Hepburn"
                        },
                        new
                        {
                            Id = 239,
                            DoctorId = 5,
                            FullName = "Barack Winslet"
                        },
                        new
                        {
                            Id = 240,
                            DoctorId = 3,
                            FullName = "Jimi Winfrey"
                        },
                        new
                        {
                            Id = 241,
                            DoctorId = 6,
                            FullName = "Charles Hepburn"
                        },
                        new
                        {
                            Id = 242,
                            DoctorId = 7,
                            FullName = "Kate Winfrey"
                        },
                        new
                        {
                            Id = 243,
                            DoctorId = 7,
                            FullName = "Kate Trump"
                        },
                        new
                        {
                            Id = 244,
                            DoctorId = 7,
                            FullName = "Kate Trump"
                        },
                        new
                        {
                            Id = 245,
                            DoctorId = 2,
                            FullName = "Mick Jagger"
                        },
                        new
                        {
                            Id = 246,
                            DoctorId = 5,
                            FullName = "Barack Obama"
                        },
                        new
                        {
                            Id = 247,
                            DoctorId = 1,
                            FullName = "Jimi Hepburn"
                        },
                        new
                        {
                            Id = 248,
                            DoctorId = 3,
                            FullName = "Donald Middleton"
                        },
                        new
                        {
                            Id = 249,
                            DoctorId = 6,
                            FullName = "Kate Jagger"
                        },
                        new
                        {
                            Id = 250,
                            DoctorId = 5,
                            FullName = "Oprah Hepburn"
                        });
                });

            modelBuilder.Entity("workshop.wwwapi.Models.Appointment", b =>
                {
                    b.HasOne("workshop.wwwapi.Models.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("workshop.wwwapi.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("workshop.wwwapi.Models.Patient", b =>
                {
                    b.HasOne("workshop.wwwapi.Models.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("workshop.wwwapi.Models.Doctor", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("workshop.wwwapi.Models.Patient", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
